// Experience supplied in Roni_Katcharovski_Resume_Software_2027.pdf, September 2026.
export const chapters={
 ford:{year:'2024',company:'Ford',vehicle:'Lincoln Nautilus',role:'Software Engineering Intern',dates:'May — August 2024',location:'Waterloo, Ontario',image:'images/ford.jpeg',caption:'Outside the Ford office.',title:'Confidence in every test.',description:'I built C++ test coverage for embedded automotive software across Ford vehicle platforms, making hardware-dependent behavior easier to validate.',work:[['500+ tests across vehicle platforms','Wrote more than 500 C++ unit tests with Google Test, achieving 98% code coverage.'],['Simulating the real dependencies','Mocked kernel system calls and asynchronous hardware drivers with Google Mock, achieving 100% function coverage.']],metrics:[['500+','C++ unit tests'],['98%','code coverage'],['100%','function coverage']]},
 cybertruck:{year:'2025',company:'Tesla',vehicle:'Cybertruck',role:'Software Engineering Intern',dates:'September — December 2025',location:'Sparks, Nevada',image:'images/tesla-reno.jpeg',caption:'With the Tesla team in Reno.',title:'Software that puts hardware to the test.',description:'I developed Go test infrastructure for Tesla Energy hardware, taking test software from requirements and implementation through manufacturing deployment.',work:[['Concurrent test infrastructure','Supported power-converter simulation, CAN communication, digital and analog I/O, and concurrent test execution.'],['Reliable multi-channel operation','Resolved concurrent-access issues in a Go driver for a three-channel power supply using mutex synchronization and error propagation.'],['Reusable ECU modules','Implemented abstractions for UDS routines, CAN I/O, and I2C-over-CAN sensor communication, expanding automated battery-management-system test coverage.'],['Owning delivery','Led weekly cross-functional engineering syncs while owning software development through manufacturing deployment.']],metrics:[]},
 cybercab:{year:'2026',company:'Tesla',vehicle:'Cybercab',role:'Software Engineering Intern',dates:'May — August 2026',location:'Palo Alto, California',image:'images/tesla-california.jpeg',caption:'A snapshot from the California chapter.',title:'From new product to production.',description:'I owned and shipped five manufacturing applications in Go and Python with React interfaces, taking software built on a shared framework from new product introduction through production deployment.',work:[['Automating firmware programming','Integrated automated programming workflows for embedded processors and Linux modules into production applications, eliminating manual programming steps at manufacturing stations.'],['Tools for the hardware–software loop','Built Claude Code developer tools for builds, SSH deployment, paced execution, log monitoring, and firmware flashing.'],['Less output, same workflow','Designed an internal Claude Code compression plugin that reduced generated output tokens by 55% across benchmark workloads.']],metrics:[['5','manufacturing applications shipped'],['55%','fewer generated output tokens in benchmarks']]}
};
export const whoop={role:'Software Engineering Intern',dates:'January — May 2025',location:'Boston, Massachusetts',work:[['Manufacturing testers, redesigned','Designed Raspberry Pi and STM32 manufacturing testers for wearable and charger product lines, saving $100K+ in build costs per product line and earning a Co-op Student of the Year nomination.'],['A better development loop','Built Python HIL/SIL infrastructure for remote hardware simulation, automated interaction logging, and SQLite-backed test analytics.'],['Real-time sensor acquisition','Implemented real-time IMU acquisition using DMA and idle-line interrupts, offloading sensor communication from the CPU.']]};

// Earlier experience supplied by Roni from previous résumés.
export const drivewayExperiences={
 electrium:{company:'Electrium Mobility',role:'Embedded Systems Developer',dates:'August 2023 — January 2024',location:'Waterloo, Ontario',image:'assets/experience/electrium.jpeg',caption:'Inside the Electrium electric skateboard: controllers, wiring, and embedded electronics.',title:'Getting two motors on the same wavelength.',description:'I worked on the embedded systems behind an electric skateboard, connecting its remote, controllers, and motors so they could work together in real time.',work:[['From remote to controller','Implemented UART communication between the ESC’s Bluetooth module and the remote, using VESC Tool to configure and communicate with the built-in STM32.'],['Two controllers, one ride','Integrated a dual-controller ESC system with custom JST cabling and CAN bus synchronization to coordinate the motors.'],['Control down to the circuit','Developed PWM motor-control software for dynamic speeds up to 40 km/h, and used PCB-level debugging and hardware validation to avoid $200 in costs.']]},
 exceed:{company:'Exceed Robotics',role:'Robotics Instructor',dates:'April — August 2023',location:'Thornhill, Ontario',image:'assets/experience/exceed.png',caption:'A tracked robotics platform from Exceed Robotics.',title:'Build it. Program it. Teach it.',description:'I designed robotics platforms and helped students turn circuits, code, and 3D models into working machines—making engineering something they could learn by building.',work:[['Robots from the ground up','Built custom platforms integrating sensors, actuators, and microcontrollers, with control software in C/C++, Arduino, and Python.'],['Vision, interaction, and play','Led robotics and game-development work using NumPy, Pygame, and OpenCV, including computer vision for object recognition.'],['Making engineering hands-on','Developed and delivered lessons in circuit diagrams, microcontroller programming, and 3D modeling with Autodesk Fusion 360 and Tinkercad.']]}
};
export const experienceOrder=[
 ['cybercab','2026','Tesla','Software Engineering · Palo Alto','May — August 2026'],
 ['cybertruck','2025','Tesla','Software Engineering · Sparks','September — December 2025'],
 ['whoop','2025','WHOOP','Software Engineering · Boston','January — May 2025'],
 ['ford','2024','Ford','Software Engineering · Waterloo','May — August 2024'],
 ['electrium','2023–24','Electrium Mobility','Embedded Systems Developer · Waterloo','August 2023 — January 2024'],
 ['exceed','2023','Exceed Robotics','Robotics Instructor · Thornhill','April — August 2023']
];
